CREATE TABLE `test_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`url` text NOT NULL,
	`method` varchar(10) NOT NULL,
	`config` json,
	`status` enum('completed','failed','cancelled') NOT NULL DEFAULT 'completed',
	`totalRequests` int NOT NULL,
	`successCount` int NOT NULL,
	`failCount` int NOT NULL,
	`avgLatency` int NOT NULL,
	`minLatency` int NOT NULL,
	`maxLatency` int NOT NULL,
	`p50Latency` int NOT NULL,
	`p90Latency` int NOT NULL,
	`p95Latency` int NOT NULL,
	`p99Latency` int NOT NULL,
	`throughput` int NOT NULL,
	`errorRate` int NOT NULL,
	`duration` int NOT NULL,
	`statusCodes` json,
	`businessCodes` json,
	`timeSeries` json,
	`userId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `test_records_id` PRIMARY KEY(`id`)
);
